apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
type: Opaque
stringData:
  connector.properties: |- 
    postgres_username: user_kafka
    postgres_password: user_kafka_password
    postgres_url: jdbc:postgresql://postgres_host.com:5432/database
    postgres_hostname: postgres_host.com
    postgres_port: 5432
    postgres_dbname: database