apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
type: Opaque
stringData:
  connector.properties: |- 
    postgres_username: user_kafka_lab
    postgres_password: user_kafka_password_lab
    postgres_url: jdbc:postgresql://postgres_url_lab.com:5432/database
    postgres_hostname: postgres_url_lab.com
    postgres_port: 5432
    postgres_dbname: database