apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  # connector name
  name: "ingest-src-mongodb-cdc-tables-avro-f16661f3"
  labels:
    # kafka connect cluster name
    strimzi.io/cluster: connect-cluster
spec:
  class: io.debezium.connector.mongodb.MongoDbConnector
  tasksMax: 2
  config:
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    mongodb.hosts: "rs0/localhost:27017"
    mongodb.password: "root"
    mongodb.user: "root"
    database.include.list: "dbo"
    collection.include.list: "dbo.user, dbo.payments"
    connect.backoff.initial.delay.ms: 2000
    connect.backoff.max.delay.ms: 160000
    mongodb.members.auto.discover: False
    snapshot.max.threads: 2
    initial.sync.max.threads: 2
    poll.interval.ms: 2000
    sanitize.field.names: True
