apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  # connector name
  name: "ingest-src-mysql-cdc-tables-avro"
  labels:
    # kafka connect cluster name
    strimzi.io/cluster: connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    database.hostname: "192.168.99.100"
    database.port: "3306"
    database.user: "debezium-user"
    database.password: "debezium-user-pw"
    database.server.name: "cdc-mysql" # connector name
    topic.prefix: fullfillment
    databse.include.list: "dbo"
    table.include.list: "dbo.device"
    database.history.kafka.bootstrap.servers: "kafka-cluster-kafka-bootstrap:9092"
    database.history.kafka.topic: "ddl-dbhistory-mysql-cdc-tables"
    message.key.columns: "dbo.device:id"
    tombstones.on​.delete: "true"
