apiVersion: "kafka.strimzi.io/v1beta2"
kind: KafkaConnector
metadata:
  # connector name
  name: "ingest-src-postgresql-handshake-json"
  labels:
    # kafka connect [cluster] name
    strimzi.io/cluster: connect-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSourceConnector
  tasksMax: 1
  config:
    producer.override.batch.size: 327680  
    producer.override.linger.ms: 100
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    connection.url: "${file:/opt/kafka/external-configuration/connector-config-postgresql/postgresql-credentials.properties:postgres_url}"
    connection.user: "${file:/opt/kafka/external-configuration/connector-config-postgresql/postgresql-credentials.properties:postgres_username}"
    connection.password: "${file:/opt/kafka/external-configuration/connector-config-postgresql/postgresql-credentials.properties:postgres_password}"
    connection.attempts: "2"
    table.types: "TABLE"
    query: "SELECT * FROM dbo.table"
    mode: "incrementing"
    topic.prefix: "src-postgresql-handshake-json"
    incrementing.column.name: "id"
    validate.non.null: "false"
    ##### SMT - Simple Message Transform - https://docs.confluent.io/5.5.4/connect/transforms/index.html #####
    transforms: "createKey,extractInt,InsertTopic,InsertSourceDetails" # informar quais transformações realizar
    transforms.createKey.type: "org.apache.kafka.connect.transforms.ValueToKey" # copie o valor de um campo para a key da mensagem
    transforms.createKey.fields: "id" # lista de campos da tabela que vai virar key
    transforms.extractInt.type: "org.apache.kafka.connect.transforms.ExtractField$Key" # extraia apenas a parte integer do campo
    transforms.extractInt.field: "id" # qual campo o integer vai ser extraido
    transforms.InsertTopic.type: "org.apache.kafka.connect.transforms.InsertField$Value" # insira o nome do tópico na mensagem
    transforms.InsertTopic.topic.field: "messagetopic" # nome do campo contendo o nome do topico
    transforms.InsertSourceDetails.type: "org.apache.kafka.connect.transforms.InsertField$Value" # insira um campo com informações da origem da mensagem
    transforms.InsertSourceDetails.static.field: "messagesource" # nome do campo
    transforms.InsertSourceDetails.static.value: "postgresql-dbname" # valor estatico para o campo