apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  # connector name
  name: "sink-minio-output-pyspark-counts-cities-json"
  labels:
    # kafka connect cluster name
    strimzi.io/cluster: connect-cluster
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  config:
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: "false"
    value.converter.schemas.enable: "false"
    topics: "minio-output-pyspark-counts-cities-json"
    s3.bucket.name: "kafka"
    s3.part.size: 5242880
    flush.size: 500
    rotate.schedule.interval.ms: 18000
    store.url: "http://minio.deepstorage.svc.cluster.local/"
    aws.access.key.id: "9npQpYTh6lEgMv3u"
    aws.secret.access.key: "6jZUGY3qe1dt0OdeSb9U4gI6hOUIIrvu"
    storage.class: "io.confluent.connect.s3.storage.S3Storage"
    format.class: "io.confluent.connect.s3.format.json.JsonFormat"
    schema.generator.class: "io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator"
    partitioner.class: "io.confluent.connect.storage.partitioner.TimeBasedPartitioner"
    path.format: "YYYY/MM/dd/HH"
    locale: "pt_BR"
    timezone: "America/Sao_Paulo"
    partition.duration.ms: 18000
    timestamp.extractor: "Record"
