apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  # connector name
  name: "sink-blob-storage-camel-test-json"
  labels:
    # kafka connect cluster name
    strimzi.io/cluster: connect-cluster
spec:
  class: org.apache.camel.kafkaconnector.azurestorageblobsink.CamelAzurestorageblobsinkSinkConnector
  tasksMax: 1
  config:
    # key.converter: org.apache.kafka.connect.json.JsonConverter
    # value.converter: org.apache.kafka.connect.json.JsonConverter

    key.converter: org.apache.kafka.connect.storage.StringConverter
    # value.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter

    # key.converter: "io.confluent.connect.avro.AvroConverter"
    # key.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    # value.converter: "io.confluent.connect.avro.AvroConverter"
    # value.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    # key.converter.schemas.enable: "true"
    # value.converter.schemas.enable: "true"
    
    topics: postgres.public.table_one
    # mandatory properties (for a complete properties list see the connector documentation):
    camel.kamelet.azure-storage-blob-sink.accessKey: "${file:/opt/kafka/external-configuration/connector-config-azure-blob-storage/connector.properties:azblob_account_key}"
    camel.kamelet.azure-storage-blob-sink.accountName: "${file:/opt/kafka/external-configuration/connector-config-azure-blob-storage/connector.properties:azblob_account_name}"
    camel.kamelet.azure-storage-blob-sink.containerName: teste-kafka-camel-connector
    camel.kamelet.azure-storage-blob-sink.operation: uploadBlockBlob
    camel.kamelet.azure-storage-blob-sink.credentialType: SHARED_ACCOUNT_KEY
    camel.aggregation.size: 5
    camel.aggregation.timeout: 5000
    camel.error.handler.max.redeliveries: 2
    # camel.sink.endpoint.keyName: ${date:now:yyyyMMdd-HHmmssSSS}-${exchangeId}
    # camel.sink.unmarshal: camel-jackson-avro
    # camel.dataformat.avro-jackson.unmarshal-type: com.fasterxml.jackson.dataformat.avro
    #max.num.retries: 2
    #key.ignore: True
    #type.name: "kafka-connect"
    #schema.ignore: True
