apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: src-postgresql-handshake-json
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  topicName: postgres.public.table_one
  partitions: 3
  replicas: 3
  config:
    retention.ms: 86400000 # 1 dia
    segment.bytes: 1073741824
    compression.type: lz4