apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: connect-cluster-user
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    # Kafka Connects internal topics used to store configuration, offsets or status
    - host: '*'
      resource:
        type: group
        name: connect-cluster
        patternType: literal
      operations:
        - Read
      type: allow
    - host: '*'
      resource:
        type: topic
        name: connect-cluster
        patternType: prefix
      operations:
        - Create
        - Describe
        - Read
        - Write
      type: allow
    - resource:
        type: topic
        name: oracle.
        patternType: prefix
      operations:
        - Create
        - Describe
        - Read
        - Write
      host: '*'
      type: allow
    - resource:
        type: topic
        name: postgres.
        patternType: prefix
      operations:
        - Create
        - Describe
        - Read
        - Write
      host: '*'
      type: allow
    - resource:
        type: topic
        name: mongodb.
        patternType: prefix
      operations:
        - Create
        - Describe
        - Read
        - Write
      host: '*'
      type: allow
    # Additional topics and groups used by connectors
    # Change to match the topics used by your connectors