apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service-lb
<<<<<<< HEAD
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
=======
>>>>>>> 26f404222602c26e8104aea59bc6116b451a3f9a
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: cp-schema-registry