apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service-lb
  namespace: analytics
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: cp-schema-registry