apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: enriched-sqlserver-addresses-json
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824