apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
type: Opaque
stringData:
  connector-postgresql.properties: |- 
    postgres_username: postgres_username
    postgres_password: postgres_password
    postgres_url: jdbc:postgresql://localhost:5432/dbname